### ISSUE TITLE
Bug ingesting target from MARS query

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#122]
I get the following error when I try to create a new target from an alert selected from MARS using a standard MARS filter within the TOM.  

It happens when selecting alert 111789793, for the record from the Query Results page, followed by "create target":

Request Method: | POST
-- | --
http://127.0.0.1:8000/alerts/alert/create/
2.2.3
AttributeError
'str' object has no attribute 'get'
/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/tom_alerts/brokers/mars.py in process_reduced_data, line 216
/Users/rstreet/software/phot_tom_venv3/bin/python
3.7.0
['/Users/rstreet/software/phot_tom',  '/Users/rstreet/software/eups/1.2.30/python',  '/Library/Frameworks/Python.framework/Versions/3.7/lib/python37.zip',  '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7',  '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload',  '/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages']
Fri, 19 Jul 2019 23:12:30 +0000

Internal Server Error: /alerts/alert/create/
Traceback (most recent call last):
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/core/handlers/base.py", line 155, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/tom_common/middleware.py", line 28, in process_exception
    raise exception
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/contrib/auth/mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/tom_alerts/views.py", line 144, in post
    broker_class().process_reduced_data(target, cached_alert)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/tom_alerts/brokers/mars.py", line 216, in process_reduced_data
    if not alert.get('prv_candidate'):
AttributeError: 'str' object has no attribute 'get'

**Comment by rachel3834** [comment]
It appears to have ingested the target into the TOM, but none of the survey data associated with it.
