### ISSUE TITLE
OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#130]
Context: I am running a management command to ingest a large number of Targets into Phot_TOM.  Each Target has a number of EXTRA_FIELD parameters associated with it, including:
{'name': 'gaia_source_id', 'type': 'string'},

This is an ID string of the Target star from the Gaia mission catalog, which takes the form of a 19-digit integer, e.g. 4062382967143360256.

This error occurred when I attempted to create a TargetExtra entry for this parameter:
TargetExtra.objects.create(target=target, key=key, value=value)

(Full debugging output is below)

The error seems to imply that the parameter is being treated as an integer despite being declared as a string, which would be unintuitive to a novice user.  

Eventually, I found a workaround by modifying my ingest code:
if key_type == 'string':
       TargetExtra.objects.create(target=target, key=key, value='"'+str(value)+'"')
else:
       TargetExtra.objects.create(target=target, key=key, value=value)

...but only because I know enough about SQLite to know that it can be picky about strings being in quotes.  

Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/rstreet/software/romerea_phot_tom/phot_tom/management/commands/import_stars_from_phot_db.py", line 100, in handle
    TargetExtra.objects.create(target=target, key=key, value=value)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/tom_targets/models.py", line 218, in save
    self.time_value = parse(self.value)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1358, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 654, in parse
    ret = self._build_naive(res, default)
  File "/Users/rstreet/software/phot_tom_venv3/lib/python3.7/site-packages/dateutil/parser/_parser.py", line 1229, in _build_naive
    naive = default.replace(**repl)
OverflowError: signed integer is greater than maximum

**Comment by Fingel** [comment]
@dmcollom you were talking about some refactoring around this?

**Comment by dmcollom** [comment]
@Fingel Yes. When I was investigating the issue, it looks like a `TargetExtra` that's not defined in the settings is stored multiple times and the type is intelligently guessed at when writing/reading from the database, which is what's causing the error. @rachel3834 mentioned that she'd be okay with requiring all `TargetExtra` fields to be defined in `settings.py`, otherwise it would throw an error when ingesting data.

The two issues that would need to be worked out with this solution would be as follows:

1. Undefined `TargetExtra` fields are currently used when ingesting broker targets, and there would need to be a discussion around how to address that.
2. Removal of a field from `settings.py` would result in the data remaining in the database, but with no mapping to it. We would need to ensure that it is well-documented, and likely include a warning in the comments.

Alternatively, we could simply use this issue as a place to document this pitfall, and include @rachel3834's solution.

**Comment by rachel3834** [comment]
Closing this issue as obsolete now
