### ISSUE TITLE
ModuleNotFoundError: No module named 'guardian'

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#133]
I encountered this error when starting a new tom app for the purposes of testing SOAR observations of microlensing programs. 

The TOM started out of the box just fine - I only encountered this error after I logged in.  I've not tried to modify anything yet, so this is likely to confuse new users. 

Full debugging output:

(phot_tom_venv3) Rachels-MacBook-Pro-2:demo_tom rstreet$ ./manage.py runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x108488840>
Traceback (most recent call last):
  File "/Users/rstreet/miniconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/rstreet/miniconda3/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/Users/rstreet/miniconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/Users/rstreet/miniconda3/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/rstreet/miniconda3/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/rstreet/miniconda3/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/rstreet/miniconda3/lib/python3.6/site-packages/django/apps/registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "/Users/rstreet/miniconda3/lib/python3.6/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/Users/rstreet/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'guardian'

**Comment by rachel3834** [comment]
Incidently:

(phot_tom_venv3) Rachels-MacBook-Pro-2:demo_tom rstreet$ pip install django-guardian
Requirement already satisfied: django-guardian in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (2.0.0)

**Comment by rachel3834** [comment]
Huh.  I think this is caused by the way I choose to set my api_key for the LCO portal in my TOM's settings.py:
   'LCO': {
        'portal_url': 'https://observe.lco.global',
        'api_key': str(os.environ['LCO_OBSERVE_TOKEN']),
    },
 Stupidly, I'd set the environment variable in my bash_profile, rather than in the venv's activate script.  

Setting this correctly in the activate resolves the issue.  

Bit of a potential gotcha for users though.  I think we should have some best-practices documentation on configuring tokens and secret_keys as environment variables rather than as code that could get committed to github.
