### ISSUE TITLE
ModuleNotFoundError for ANTARES

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#186]
I just updated my existing venv to the most recent version (via >pip install tomtoolkit --upgrade) but this now produces a missing module error, presumably because it has been moved to a different location.  

(The same error occurs when I create a new venv from scratch):

Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/tom_alerts/alerts.py", line 33, in get_service_classes
    mod = import_module(mod_name)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tom_alerts.brokers.antares'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/core/checks/urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/core/checks/urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/urls/resolvers.py", line 579, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/urls/resolvers.py", line 572, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/tom_common/urls.py", line 30, in <module>
    path('alerts/', include('tom_alerts.urls', namespace='alerts')),
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/tom_alerts/urls.py", line 3, in <module>
    from tom_alerts.views import BrokerQueryCreateView, BrokerQueryListView, BrokerQueryUpdateView, RunQueryView
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/tom_alerts/views.py", line 93, in <module>
    class BrokerQueryFilter(FilterSet):
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/tom_alerts/views.py", line 95, in BrokerQueryFilter
    choices=[(k, k) for k in get_service_classes().keys()]
  File "/Users/rstreet/software/tom_venv3_brew/lib/python3.7/site-packages/tom_alerts/alerts.py", line 38, in get_service_classes
    Did you provide the correct path?'''.format(service)
ImportError: Could not import tom_alerts.brokers.antares.AntaresBroker.
                Did you provide the correct path?

**Comment by dmcollom** [comment]
A recent change moved the AntaresBroker to the tom_antares repo and associated PyPi package. The additional packages are documented [here](https://tom-toolkit.readthedocs.io/en/stable/modules/plugins.html).

To fix this issue, either remove `tom_alerts.brokers.antares.AntaresBroker` from `TOM_ALERT_BROKERS` in `settings.py`, or do a `pip install tom_antares` and replace the aforementioned setting with `tom_antares.antares.AntaresBroker`.

We certainly recognize that we should communicate better and will include changes like these in future release notes.
