### ISSUE TITLE
migrations.exceptions.NodeNotFoundError on upgrade to 1.2.1

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#225]
**Describe the bug**
Using the runserver command exits with an error (below) complaining about a missing migration. 

**To Reproduce**
Within my virtualenv (without updating to Django v3.0), I used pip to upgrade to the latest version of the Toolkit.  This completed normally, but when I runserver I now get:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/utils/autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check_migrations()
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/core/management/base.py", line 453, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/db/migrations/loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/Users/rstreet/software/tom_venv3/lib/python3.7/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration tom_dataproducts.0008_merge_20191115_0010 dependencies reference nonexistent parent node ('tom_dataproducts', '0003_merge_20190520_1645')

I also attempted to makemigrations but the process exited with the same error.  

**Expected behavior**
If a migration is required for this update, I'd expect it to be included in the release and build using the makemigrations command.  

**Screenshots**
None applicable. 

**Desktop (please complete the following information):**
 - OS Catalina 10.15.1

**Additional context**
None

**Comment by dmcollom** [comment]
After doing some investigating into Rachel's environment, it has been determined that the offending migration (0008_merge_20191115_0010) never existed in any TOM Toolkit releases and was possibly incidentally created by Rachel. I was unable to reproduce it in a clean TOM, or while upgrading from 1.2.0 to 1.2.1.

The correct fix for any that also run into this issue is to remove any migrations beyond `tom_dataproducts/migrations/0007_manual_20191016_rename_type.py` from `lib/python3.x/site-packages and lib64/python3.x/site-packages`, if applicable. That migration was the last officially released `tom_dataproducts` migration. If another person happens to come across this, feel free to re-open the issue.

**Comment by dmcollom** [comment]
This was re-opened due to Etienne experiencing the same issue. After some investigation, it was determined that the old migrations were still in our local `build` directories and being included in the .whl of the PyPi release. After uploading a clean version, the migrations work both from a fresh 1.2.4 install and upgrading from 1.2.3 to 1.2.4.
