### ISSUE TITLE
Cannot export targets if no alias

### ISSUE THREAD

**Issue by TimotheeGr** [TOMToolkit/tom_base#265]
**Bug description**
I get an error when I try to export targets that have no "alias".

**To Reproduce**
If all the targets I created have only a name, right ascension and declination (in particular no alias), *even the targets that I don't filter* must have no alias to reproduce this bug. 
Then by clicking on Export Filtered Targets button I get:
```
Environment:


Request Method: GET
Request URL: https://amontom.science.psu.edu/targets/export/?type=&name=&key=&value=&cone_search=&targetlist__name=1&target_cone_search=&energy_min=&energy_max=

Django Version: 2.2.7
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_extensions',
 'guardian',
 'tom_common',
 'django_comments',
 'bootstrap4',
 'crispy_forms',
 'django_filters',
 'django_gravatar',
 'tom_targets',
 'tom_alerts',
 'tom_catalogs',
 'tom_observations',
 'tom_dataproducts']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'tom_common.middleware.ExternalServiceMiddleware']



Traceback:

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  34.             response = get_response(request)

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  115.                 response = self.process_exception_by_middleware(e, request)

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/handlers/base.py" in process_exception_by_middleware
  155.             response = middleware_method(request, exception)

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/tom_common/middleware.py" in process_exception
  28.         raise exception

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  113.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/views/generic/base.py" in view
  71.             return self.dispatch(request, *args, **kwargs)

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/views/generic/base.py" in dispatch
  97.         return handler(request, *args, **kwargs)

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django_filters/views.py" in get
  87.         return self.render_to_response(context)

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/tom_targets/views.py" in render_to_response
  394.         file_buffer = export_targets(qs)

File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/tom_targets/utils.py" in export_targets
  29.                            in TargetName.objects.values('target_id').annotate(count=Count('target_id'))])

Exception Type: ValueError at /targets/export/
Exception Value: max() arg is an empty sequence
```

**Comment by dmcollom** [comment]
Hi @TimotheeGr,

Thanks for the issue report! The fix for this has been released, and is included in version 1.4.0. When you upgrade, be sure to read the [release notes](https://github.com/TOMToolkit/tom_base/releases/tag/1.4.0)--you'll need to add a value to your settings.py to ensure compatibility.

Let me know if this doesn't fix the problem you're seeing!

**Comment by TimotheeGr** [comment]
That was very fast! Thanks a lot!

However I have problems when upgrading to 1.4.0. I have added to the settings what is suggested in the release notes, I also added 'tom_publications' to the installed_apps as I get an error suggesting to do so (`Model class tom_publications.models.LatexConfiguration doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`).
Now I have `no such column: tom_targets_target.epoch_of_elements` when I want to access the home page:

```Environment:


Request Method: GET
Request URL: https://amontom.science.psu.edu/

Django Version: 3.0.4
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sites',
 'django_extensions',
 'guardian',
 'tom_common',
 'django_comments',
 'bootstrap4',
 'crispy_forms',
 'django_filters',
 'django_gravatar',
 'tom_targets',
 'tom_alerts',
 'tom_catalogs',
 'tom_observations',
 'tom_dataproducts',
 'tom_publications']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'tom_common.middleware.ExternalServiceMiddleware']


Template error:
In template /var/www/amonTOM/tom_env/lib/python3.6/site-packages/tom_targets/templates/tom_targets/partials/recent_targets.html, error at line 4
   no such column: tom_targets_target.epoch_of_elements
   1 : <table class="table">
   2 :   <thead><tr><th>ID</th><th>Created</th></tr></thead>
   3 :   <tbody>
   4 :      {% for target in targets %} 
   5 :     <tr>
   6 :       <td>
   7 :         <a href="{% url 'targets:detail' target.id %}" title="Detail for {{ target.name }}">
   8 :           {{ target.name }}
   9 :         </a>
   10 :       </td>
   11 :       <td>
   12 :         {{ target.created|date }}
   13 :       </td>
   14 :     </tr>


Traceback (most recent call last):
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)

The above exception (no such column: tom_targets_target.epoch_of_elements) was the direct cause of the following exception:
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 155, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/tom_common/middleware.py", line 29, in process_exception
    raise exception
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/library.py", line 234, in render
    return t.render(new_context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 173, in render
    return self._render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 936, in render
    bit = node.render_annotated(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/base.py", line 903, in render_annotated
    return self.render(context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/template/defaulttags.py", line 166, in render
    len_values = len(values)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/models/query.py", line 57, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1151, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 396, in execute
    return Database.Cursor.execute(self, query, params)

Exception Type: OperationalError at /
Exception Value: no such column: tom_targets_target.epoch_of_elements
```
And the admin page (or other accessible pages) looks like 
![Capture d’écran de 2020-03-31 10-45-34](https://user-images.githubusercontent.com/51410054/78040514-87fe2300-733d-11ea-91a0-2e958fb86184.png)

**Comment by dmcollom** [comment]
Ah, I think I know what this is. I'm not sure what version you were previously on, but either in this version or the last, a new field was added to Target. This means that a migration is required--in all likelihood, when you start up your TOM, you probably see a message something like "you have unapplied migrations". This is a very typical thing with Django projects.

All you should need to do is stop your TOM and run ./manage.py migrate. That _should_ fix it, but if it doesn't, I can certainly help debug further.

**Comment by dmcollom** [comment]
Oh, and your tom_publications issue (sorry, I missed that!)--let's see what happens after you migrate.

**Comment by TimotheeGr** [comment]
The migration gives me 
```
Traceback (most recent call last):
  File "./manage.py", line 21, in <module>
    main()
  File "./manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/migrations/loader.py", line 274, in build_graph
    raise exc
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/migrations/loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/migrations/graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/migrations/graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "/var/www/amonTOM/tom_env/lib/python3.6/site-packages/django/db/migrations/graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration tom_dataproducts.0008_merge_20191126_1647 dependencies reference nonexistent parent node ('tom_dataproducts', '0003_merge_20190520_1645')
```
I hope I do this well, I am not sure how to stop or start up my TOM (I mean I don't see "you have unapplied migrations"), I am on a server I stopped apache but it is probably not what you mean. Sorry, I started that months ago and I am just comming back on it, I forgot some of it.

**Comment by dmcollom** [comment]
Actually, you did exactly what you should have. Sorry for the inconvenience!

I actually remember us dealing with this a while back--there's a prior issue for this exact problem in 1.2.0: https://github.com/TOMToolkit/tom_base/issues/225

The quickest potential fix would be to remove the offending migrations from `lib/python3.x/site-packages` and `lib64/python3.x/site-packages`. As you can see in the previous bug report, we may need to do something else, but this is step 1, if you don't mind doing it. Happy to provide further guidance if you need it, and I can walk you through it on Slack if that's easier.

Also, if you don't have any critical data in your TOM, it might be easier to just recreate your database and run all migrations again, but that's very much up to you. We'll help you figure this out one way or another.

**Comment by TimotheeGr** [comment]
Great! It solved the problem! Thanks a lot!
