### ISSUE TITLE
Error in Alerce Alert Cone search

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#691]
stack trace:

```Fetching alerts from ALeRCE with payload [('page', 1), ('page_size', 20), ('ra', 58.4856794), ('dec', 48.38026336), ('radius', 5)]
Internal Server Error: /alerts/query/18/run/
Traceback (most recent call last):
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/base.py", line 199, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/home/jchatelain/git/tom_base/tom_common/middleware.py", line 29, in process_exception
    raise exception
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
  File "/home/jchatelain/git/tom_base/tom_alerts/views.py", line 231, in get_context_data
    alert_query_results = broker_class.fetch_alerts(deepcopy(query.parameters))
  File "/home/jchatelain/git/tom_base/tom_alerts/brokers/alerce.py", line 320, in fetch_alerts
    if len(alerts) > 0 and response['page'] < parameters.get('max_pages', 1):
TypeError: '<' not supported between instances of 'NoneType' and 'int'
Internal Server Error: /alerts/query/18/run/
Traceback (most recent call last):
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/base.py", line 199, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/home/jchatelain/git/tom_base/tom_common/middleware.py", line 29, in process_exception
    raise exception
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/base.py", line 226, in get
    context = self.get_context_data(**kwargs)
  File "/home/jchatelain/git/tom_base/tom_alerts/views.py", line 231, in get_context_data
    alert_query_results = broker_class.fetch_alerts(deepcopy(query.parameters))
  File "/home/jchatelain/git/tom_base/tom_alerts/brokers/alerce.py", line 320, in fetch_alerts
    if len(alerts) > 0 and response['page'] < parameters.get('max_pages', 1):
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```
This looks to be a change in the `response.json()` from Alerce with respect to `page`.

**Comment by jchate6** [comment]
This seems to be a bug on the ALeRCE side.
Pagination does not seem to work properly without `count=true` and even then no `page` is provided.
