### ISSUE TITLE
Out the Box TOM unable to create LCO observation Template

### ISSUE THREAD

**Issue by jchate6** [TOMToolkit/tom_base#725]
From @zemogle:
"I’ve just done a fresh install of TOM toolkit on my sandbox and get a 500 error when I try to create an observation template."
![image](https://github.com/TOMToolkit/tom_base/assets/32683393/9a792a86-1582-438c-b3a4-68fe4471007a)
"`/api/profile/` doesn’t appear in the registered list of URLs, so I’m not sure what happened here."

Reproducing locally:
```[30/Oct/2023 18:56:03] "GET /observations/template/list/ HTTP/1.1" 200 5438
Internal Server Error: /observations/template/LCO/create/
Traceback (most recent call last):
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/base.py", line 199, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/home/jchatelain/git/tom_base/tom_common/middleware.py", line 29, in process_exception
    raise exception
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/edit.py", line 74, in get_context_data
    kwargs["form"] = self.get_form()
  File "/home/jchatelain/git/tom_base/tom_observations/views.py", line 613, in get_form
    form = super().get_form()
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/django/views/generic/edit.py", line 39, in get_form
    return form_class(**self.get_form_kwargs())
  File "/home/jchatelain/git/tom_base/tom_observations/facilities/ocs.py", line 277, in __init__
    self.fields['proposal'] = forms.ChoiceField(choices=self.proposal_choices())
  File "/home/jchatelain/git/tom_base/tom_observations/facilities/ocs.py", line 256, in proposal_choices
    response = make_request(
  File "/home/jchatelain/git/tom_base/tom_observations/facilities/ocs.py", line 158, in make_request
    response = requests.request(*args, **kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/home/jchatelain/git/tom_base/env_tombase/lib64/python3.10/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL '/api/profile/': No scheme supplied. Perhaps you meant https:///api/profile/?

**Comment by jchate6** [comment]
It looks like the LCO Facility that extends the OCS Facility is still trying to use the OCS Facility `portal_url` rather than its own.
This is causing a failure when no OCS Facility dictionary exists in `settings.FACILITIES`.
