### ISSUE TITLE
TOMToolkit interacting weirdly with Django development server (`runserver`) reloader

### ISSUE THREAD

**Issue by phycodurus** [TOMToolkit/tom_base#925]
Workaround: stop the current development server (`runserver`) (ctrl-C) and restart (`./manage.py runserver`)

This seems to have been introduced sometime around TOMToolkit 2.18.0 or so:
When, during TOM development, the Django reloader notices a source file change and restarts the development server the following traceback occurs: (see below, actually)

This also occurs when there is a syntax error in the change that triggered the reload, obscuring the error that should normally be displayed. This complicates correcting what is probably an otherwise trivial typo.

----------------------------
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/TOM_eso_2024Apr03_0134/urls.py", line 19, in <module>
    path('', include('tom_common.urls')),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/llindstrom/dev/tom_base/tom_common/urls.py", line 34, in <module>
    router.register(r'groups', GroupViewSet, 'groups')
  File "/home/llindstrom/dev/tom_base/tom_common/api_router.py", line 14, in register
    self.shared_router.register(*args, **kwargs)
  File "/home/llindstrom/dev/TOM_eso_2024Apr03_0134/env/lib/python3.11/site-packages/rest_framework/routers.py", line 59, in register
    raise ImproperlyConfigured(msg)
django.core.exceptions.ImproperlyConfigured: Router with basename "groups" is already registered. Please provide a unique basename for viewset "<class 'tom_common.api_views.GroupViewSet'>"
`

**Comment by jchate6** [comment]
This is not an issue that I'm seeing. (Fedora 39)
Are you saying that when you checkout a tomtoolkit version < 2.18.0 this doesn't happen?

**Comment by phycodurus** [comment]
> Are you saying that when you checkout a tomtoolkit version < 2.18.0 this doesn't happen?
I'm saying that never happened until it started happening around that time (not sure exactly when)

**Comment by jchate6** [comment]
Does it happen for other django projects, or just tomtoolkit?

**Comment by jchate6** [comment]
I believe this is connected to `python3.11`
This does not seem to occur with `python3.10`

**Comment by DurhamJohnAPaice** [comment]
I can confirm that this is also happening with my TOMToolkit, and I am also running `python3.11`.

**Comment by phycodurus** [comment]
Fixed by https://github.com/TOMToolkit/tom_base/pull/953
