### ISSUE TITLE
API Query for Target containing NaN, -Inf, Inf resulting in `ValueError: Out of range float values are not JSON compliant` and giving a 500 error

### ISSUE THREAD

**Issue by rachel3834** [TOMToolkit/tom_base#978]
**Describe the bug**
I have a data pipeline with a function designed to upload target lightcurves (in CSV format) to my TOM, using the TOM's APIs. 
Specifically, it uses [this module](https://github.com/pyDANDIA/pyDANDIA/blob/old_ref_astro/pyDANDIA/upload_lc_to_tom.py) for the upload, which calls the TOM functions in the pipeline's [tom.py module.](https://github.com/pyDANDIA/pyDANDIA/blob/old_ref_astro/pyDANDIA/tom.py)  

The issue is raised in tom.get_target_id when the server returns a 500 status code.  

**To Reproduce**

Nothing was logged in stern when I tested this with MOP in operation, so investigating this on my test server, I re-created the query:

targetid_url = BASE_URL/api/targets/
params = {'name': 'OGLE-2024-GD-0006'} (as an example)

```
response = requests.get(targetid_url, auth=login, params=ur)
```

The trackback from my test server is as follows:
```
Internal Server Error: /api/targets/
Traceback (most recent call last):
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 222, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/data/software/mop_venv/lib/python3.10/site-packages/tom_common/middleware.py", line 29, in process_exception
    raise exception
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/data/software/mop_venv/lib/python3.10/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/data/software/mop_venv/lib/python3.10/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/data/software/mop_venv/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
Internal Server Error: /api/targets/
Traceback (most recent call last):
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 222, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 362, in process_exception_by_middleware
    response = middleware_method(request, exception)
  File "/data/software/mop_venv/lib/python3.10/site-packages/tom_common/middleware.py", line 29, in process_exception
    raise exception
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/data/software/mop_venv/lib/python3.10/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/data/software/mop_venv/lib/python3.10/site-packages/rest_framework/response.py", line 74, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/data/software/mop_venv/lib/python3.10/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/data/software/mop_venv/lib/python3.10/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

**Expected behavior**
This module of the pipeline has been uploading lightcurve data for some time, and hasn't changed recently, so it seems likely this is related to implementing the custom target model.

**Comment by rachel3834** [comment]
Interestingly, manually uploading the same CSV lightcurve file via the Manage Data tab works fine.

**Comment by jchate6** [comment]
@rachel3834 Can you confirm for me that OGLE-2024-GD-0006 has either a NaN or an inf in one of it's float fields?

**Comment by rachel3834** [comment]
Looking at the target through the admin interface, I don't see any
parameter values that are NaN or inf or otherwise out of bounds.  That
said, I am not sure how Django's admin interface would render NaN or inf
values.  But long story short, there is nothing obviously wrong with this
target.  Also, we are seeing the same error for all lightcurve uploads
through the API, so I don't think it is specific to this object.

**Comment by jchate6** [comment]
Unfortunately the admin interface will translate a NaN as an empty field.
If you could do a command line query for that target and check the results that would be interesting.

When I try to retrieve `Gaia24bqa` from MOP using requests, I get a success.
When I try to retrieve 'OGLE-2024-GD-0006' it returns a 500 error.

The error you show above, `ValueError: Out of range float values are not JSON compliant` implies that one of the target Float fields has a numpy NaN or inf stored in it and these are not JSON compatible.

**Comment by rachel3834** [comment]
Ah-ha!  Through the management shell, I can see that the target's
interferometry_interval has indeed been set to inf.  Technically, this is
still a valid, meaningful setting for this parameter. But I guess this is
causing the 500 error.  So what 'null' value would you recommend?

**Comment by jchate6** [comment]
Excellent. 
This is not an unheard of issue. Let me do some research and figure out the best way to handle this.

**Comment by jchate6** [comment]
@rachel3834 can you please add `'STRICT_JSON': False` to your `REST_FRAMEWORK` dictionary in `settings.py`?

Should look something like:
```
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
    ],
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'STRICT_JSON': False,
}
```

And try again to access your targets.

**Comment by rachel3834** [comment]
Testing this on my localhost MOP, this settings change seems to solve the problem.  Will now test in deployment.
